class Solution {
public:
    int nthUglyNumber(int n) {
        
        vector<int>v(n);
            
        v[0]=1;
        
        int p1=0,p2=0,p3=0,i;
        for(i=1;i<n;i++)
        {
            v[i]=min({v[p1]*2,v[p2]*3,v[p3]*5});
             if(v[i] == v[p1]*2) p1++; 
            if(v[i] == v[p2]*3) p2++;
            if(v[i] == v[p3]*5) p3++;
        }
        /*
        Each number can be and have to be generated by a former number multiplied by 2, 3 or 5
        
        */
        return v[n-1];
        
    }
};